version: "3.9"

services:
  merchandise-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: merchandise-service
    hostname: merchandise-service
    ports:
      - "8080:80"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5428;Database=merchandise-service;Username=postgres;Password=merchandiseService;"
      StockApiGrpcConnectionOptions__ConnectionString: "host.docker.internal:5002"
    depends_on:
      - merchandise-service-db
    restart: unless-stopped

  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=stock-api;Username=postgres;Password=stockApiPassword;"
    depends_on:
      - stock-api-db
    restart: unless-stopped
        
  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Database=supply-service;Username=postgres;Password=supplyServicePassword;"
    hostname: supply-service
    depends_on:
      - supply-service-db
    restart: unless-stopped

  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5425;Database=employees-service;Username=postgres;Password=employeesServicePassword;"
    hostname: employees-service
    depends_on:
      - employees-service-db
    restart: unless-stopped

  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service
    
  employees-service-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: employeesServicePassword
      POSTGRES_DB: employees-service

  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service

  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api

  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseService
      POSTGRES_DB: merchandise-service