version: "3.9"

services:
  merchandise-service:
    build:
      context: ../
      dockerfile: Dockerfile
    image: merchandise-service
    hostname: merchandise-service
    ports:
      - "8080:80"
      
  emailing-service:
    hostname: emailing-service
    image: "ghcr.io/ozon-edu-csharp-2021/emailing-service:main"
    
  employees-service:
    hostname: employees-service
    image: "ghcr.io/ozon-edu-csharp-2021/employees-service:main"
  stock-api:
    hostname: stock-api
    image: "ghcr.io/ozon-edu-csharp-2021/stock-api:main"
    
  supply-service:
    hostname: supply-service
    image: "ghcr.io/ozon-edu-csharp-2021/supply-service:main"